---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mjchar

<!-- badges: start -->
<!-- badges: end -->

mjcharは[文字情報技術促進協議会](https://moji.or.jp)による[文字情報基盤整備事業](https://moji.or.jp/mojikiban/)で整備された漢字文字集合であるMJ文字についての情報検索を行うRパッケージです。

本パッケージが提供するMJ文字情報の一覧データは[情報処理推進機構(IPA)](https://www.ipa.go.jp/)ならびに文字情報技術促進協議会の著作物です。[クリエイティブ・コモンズ 表示 – 継承 2.1 日本 ライセンス](https://creativecommons.org/licenses/by-sa/2.1/jp/)により配布されています。

## インストール

現在、mjcharはCRANには登録されていませんが、次のコマンドを実行することで インストールが可能です。

``` r
install.packages("mjchar", repos = "https://uribo.r-universe.dev")
```

## 利用方法

```{r}
library(mjchar)
```

```{r}
(x <- "\U74dc")

(y <- "\U771f")
```

### MJ文字情報

漢字についての情報を確認することができます。

```{r}
# 文字情報基盤検索システムへのリンクを表示します
search_mojikiban(x, input_type = "font")

moji_to_mjcode(x)

moji_information(y)
```

### 漢字の使われ方

- 読み
- 漢字施策: 対象の漢字が常用漢字・人名用漢字に含まれるかを判定します。
- 画数、部首の確認

```{r}
moji_to_yomi(x)
moji_to_yomi(y)
```

```{r}
is_jyouyou_kanji(x)
is_jyouyou_kanji(y)

is_jinmeiyou_kanji(x)
is_jinmeiyou_kanji(y)
```

```{r}
kakusu("\U74DC")
busyu("\U74DC")
```

